---
- name:         VNF Inventory
  hosts:        localhost
  gather_facts: yes
  become:       no
  connection:   local

  # ----- VARS -----------------------------------------------------------------

  vars:
    vnf:         "example"
    repo_prefix: "http://gitlab/Applications"

  # ----- TASKS ----------------------------------------------------------------

  tasks:
  - name: Create Task UUID
    set_fact:
      uuid: "{{ 1000000000 | random | to_uuid }}"

  - name: Load VNF Descriptor
    uri:
      url:            "{{repo_prefix}}/{{vnf}}/raw/master/playbook_parameters.yml"
      validate_certs: no
      return_content: yes
    ignore_errors: yes
    changed_when:  false
    register:      descriptor

  - name: Validating VNF Descriptor
    fail:
      msg: "Unable to load descriptor"
    when: descriptor.status != 200
    changed_when: false

  - name: Load VNF Credentials
    set_fact:
      vnfd: "{{ descriptor.content | from_yaml }}"

  - name: Load Cloud Credentials
    set_fact:
      cloud: "{{ clouds.get( vnfd.tenant.cloud ) }}"

  - name: Create Customer clouds.yml Configuration
    template:
      src:  clouds.yml.j2
      dest: "/tmp/{{uuid}}.yml"
    changed_when: false

  - name: Check Connectivity
    wait_for:
      host: "{{ cloud.auth.auth_url | urlsplit('hostname') }}"
      port: "{{ cloud.auth.auth_url | urlsplit('port') }}"
      timeout: 1
      msg: "Unable to connect to Cloud API"

  - name: Install Shade
    pip:
      name: shade

  - name: Obtain Inventory Data (may take some time)
    script: ./scripts/inventory.py
    environment:
      OS_CLIENT_CONFIG_FILE: "/tmp/{{uuid}}.yml"
      OS_CLOUD:              "{{vnfd.tenant.cloud}}"
      OS_VNF_NAME:           "{{vnfd.vnf.name}}"
      OS_PROJECT_NAME:       "{{vnfd.tenant.name}}"
      OS_PASSWORD:           "{{ vnfd.tenant.password }}"
    register: data
    changed_when: false

  - name: Get Timestamp
    set_fact:
      timestamp: "{{ ansible_date_time.epoch }}"

  - name: Upload Inventory
    script: ./scripts/upload.sh
    environment:
      PROJECT:  "Applications/{{vnf}}"
      LOCATION: "inventory/{{timestamp}}"
      CONTENT:  "{{data.stdout}}"
    register: result
    changed_when: false
